export const GET_ALL_POLL_REQUEST = "GET_ALL_POLL_REQUEST"
export const GET_ALL_POLL_SUCCESS = "GET_ALL_POLL_SUCCESS"
export const GET_ALL_POLL_ERROR = "GET_ALL_POLL_ERROR"

export const GET_APPROVED_QUESTIONS_REQUEST = "GET_APPROVED_QUESTIONS_REQUEST"
export const GET_APPROVED_QUESTIONS_SUCCESS = "GET_APPROVED_QUESTIONS_SUCCESS"
export const GET_APPROVED_QUESTIONS_ERROR = "GET_APPROVED_QUESTIONS_ERROR"

export const QUESTION_APPROVE_REQUEST = "QUESTION_APPROVE_REQUEST"
export const QUESTION_APPROVE_SUCCESS = "QUESTION_APPROVE_SUCCESS"
export const QUESTION_APPROVE_ERROR = "QUESTION_APPROVE_ERROR"